### ISSUE TITLE
SMT Solver: "Can't find variable: SharedArrayBuffer" error when running

### ISSUE THREAD

**Issue by nigar-azhar** [se-buw/fm-playground#10]
I'm encountering an issue when trying to run the SMT solver on the FM Playground. The error message displayed is:
![image](https://github.com/user-attachments/assets/b1b29eb0-edd4-4ed0-b57f-9522d526552a)

**Steps to reproduce:**

1. Navigate to the SMT solver.

![image](https://github.com/user-attachments/assets/c4718153-c7b4-4e50-be31-67c5a71dac18)

2. Execute the solver.
3. Observe the error message.

**Expected behavior:** The SMT solver should execute without encountering any errors.

**Actual behavior:** The above error message is displayed, preventing the solver from running properly.

**Environment:**

Browser: Safari (Version 17.6)
Operating System: macOS Monterey version 12.7.6

Please note that it works fine on Firefox 130.0 (64-bit) on the same system.

Please let me know if more details are needed. Thanks!

**Comment by soaibsafi** [comment]
In the playground, SharedArrayBuffer is utilized for the Z3 Webassembly threading. It seems like some [cross-origin (COOP, COEP) headers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) needed to be configured. 
I configured this and tested it on iOS Safari (17.5.1). However, I don't have access to a MacBook now, so I couldn't debug it. Could you confirm whether the problem persists?
