### ISSUE TITLE
Can't use new lines in formula

### ISSUE THREAD

**Issue by ask1234560** [se-buw/fm-playground#14]
Getting error for using new lines.

Steps to reproduce-
- Go to the `Validity Example` in the guides
- Check for satisfiability and click on run

Find the screenshot of the issue
![image](https://github.com/user-attachments/assets/b5c8aa19-eec2-423a-a932-b757cde29ba2)

**Comment by soaibsafi** [comment]
Should be resolved now.

https://play.formal-methods.net/?check=SAT&p=mutate-garter-heap-spiral

**Comment by ask1234560** [comment]
Thanks
