### ISSUE TITLE
Limboole parsing and parenthesis

### ISSUE THREAD

**Issue by jringert** [se-buw/fm-playground#4]
There is some strange behavior with parsing of Limboole either in the frontend or in general:

- [This formula](https://play.formal-methods.net/?check=SAT&p=pucker-travel-fedora-prize) clearly has an issue with too many parentheses in the last line, however, removing them produces syntax errors.
- [When removing the quotation marks](https://play.formal-methods.net/?check=SAT&p=derby-snitch-croon-womb) in the comment in l. 2, the parenthesis parsing appears to work as expected.

**Comment by soaibsafi** [comment]
It seems like the problem is with Unicode character parsing (replacing the smart quote (“) with a normal quote (") solves the issue). Even though the native code can handle the Unicode characters, either web assembly or JavaScript raises the issue during parsing.
